appenders:
  my_stdout:
    kind: console
    encoder:
      pattern: "{h({d(%Y-%m-%d %H:%M:%S)(utc)} - {l}: {m}{n})}"
  default_logger:
    kind: rolling_file
    path: "log/compiler-be.log"
    encoder:
      pattern: "{d(%Y-%m-%d %H:%M:%S)(utc)} - {h({l})}: {m}{n}"
    policy:
      trigger:
        kind: size
        limit: 500kb
      roller:
        kind: fixed_window
        base: 1
        count: 10
        pattern: "log/compiler{}.log"
root:
  level: info 
  appenders:
    - my_stdout
loggers:
  compiler:
    level: info 
    appenders:
      - default_logger
